### ISSUE TITLE
TOTP and HOTP parameters mismatch

### ISSUE THREAD

**Issue by XFox111** [linuxgemini/otpauth-spec-draft#2]
## Counter parameter
Is paragraph 3.3.4 it is recommended to specify `counter` parameter for both TOTP and HOTP which contradicts with TOTP specification (RFC 2638) which doesn't use `counter` parameter at all (instead it uses it Unix time as a base for calculating current counter).

### Proposal
Explicitly state that this parameter is used only by HOTP authenticators and is not supported (or ignored) by TOTP. The text should read the following:
```
3.3.4. counter parameter (REQUIRED if HOTP)
The provisioning counter for HOTP tokens MUST BE provided in this parameter.

This parameter is ignored if the token type is TOTP.
```

## Period parameter
It is the same issue in paragraph 3.3.5 but the other way around. The `period` is only used in TOTP (per RFC 2638) in order to calculate the counter. HOTP instead uses `counter` as-is without any alterations.

### Proposal
Explicitly state that this parameter is used only by TOTP authenticators and is not supported (or ignored) by HOTP. The text should read the following:
```
3.3.5. period parameter (OPTIONAL, only TOTP)
The refresh period (in seconds) for TOTP tokens SHOULD BE provided in this parameter. When not provided, 30 seconds is assumed by default.

This parameter is ignored if the token type is HOTP.
```

I can submit a PR for that, if it's ok.

**Comment by linuxgemini** [comment]
Hi! Sorry for the delay; if you want to submit a PR, feel free to do so.
